spring:
  datasource:
    url: jdbc:mysql://rm-m5e7523t24326u9638o.mysql.rds.aliyuncs.com/gas?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    #url: jdbc:mysql://localhost/gas?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    #serverTimezone=UTC
    #url: jdbc:mysql://127.0.0.1:3306/ysh_dev?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    #password: 123456
    password: Lianfukeji666
    driverclassname: com.mysql.cj.jdbc.Driver



mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.lianfu.gasserversys.mode.*
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true






server:
  port: 8080
  servlet:
    context-path: /gasserversys

